name: Pipeline Feedback

on:
  push:
    branches:
      - main

jobs:
  pipeline-feedback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      # Install Python and dependencies
      - name: Set up Python and Install Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run exercise feedback
      - name: Pipeline feedback
        run: |
          ./project/test.sh
